### ISSUE TITLE
Remove Unnecessary Files

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-zmq#4]
Review scenes, scripts, etc for removal

* tunnel.bat
* Dockerfile
* oplsaa.xml (think it just added tip4p?)
* Sprites
* Ring materials

**Comment by hgandhi2411** [comment]
The oplsaa file is required for the forcefield. We use the hoomd_ff script which you developed for htf applications @whitead. Other files can be removed safely.

**Comment by whitead** [comment]
That file is included within one of the dependencies (mbuild or foyer I think). I only made a copy so I could add the tip4p water model to the file. It might make more sense to remove it then, since we won't be using tip4p.

**Comment by hgandhi2411** [comment]
Addressed by #5
